PierreTreats/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PierresTreats.Models;


public class Treat
{
  public int TreatId { get; set; }
  [Required(ErrorMessage = "Please enter a name for the treat.")]
  public string TreatName { get; set; }
  public List<FlavorTreat> JoinEntities { get; set; }

   public ApplicationUser User { get; set; } 

}

PierreTreats/Controllers/FlavorsController.cs
using System.Net.Mail;
using System.Reflection.PortableExecutable;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using PierresTreats.Models;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager; 

    public FlavorsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Flavors.ToList());
    }
    public async Task<ActionResult> MyFlavor()
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      List<Flavor> userItems = _db.Flavors
                          .Where(entry => entry.User.Id == currentUser.Id)
                          .Include(item => item.Treat)
                          .ToList();
      return View(userItems);
    }


    public ActionResult Create()
    {
      return View();
    }

      [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
      if (!ModelState.IsValid)
      {
        
        ViewBag.FlavorId = new SelectList(_db.Treats, "TreatId", "TreatName");
        return View(flavor);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        flavor.User = currentUser;
        
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }
    
    public ActionResult Details(int id)
    {
      Flavor ThisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(flavor => flavor.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);

      return View(ThisFlavor);
    }

    public ActionResult Edit(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);

    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Flavors.Update(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

      public ActionResult Delete(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor= _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
        Flavor thisFlavor = _db.Flavors
                              .Include(fish => fish.JoinEntities)
                              .ThenInclude(join => join.Treat)
                              .FirstOrDefault(flavors => flavors.FlavorId == id);
        ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
        return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat (Flavor flavor, int treatId)
    {
    #nullable enable
        FlavorTreat? joinEntity = _db.FlavorTreats
                                  .FirstOrDefault(join => (join.TreatId == treatId 
                                  && join.FlavorId == flavor.FlavorId));
    #nullable disable
        if(joinEntity == null && treatId != 0)
        {
            _db.FlavorTreats.Add(new FlavorTreat() {TreatId = treatId, FlavorId = flavor.FlavorId});
            _db.SaveChanges();
        }  
        return RedirectToAction("Details", new { id = flavor.FlavorId});

        }

      [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }




    }
  }

PierreTreats/Controllers/TreatsController.cs
using System.Net.Mail;
using System.Reflection.PortableExecutable;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;


using PierresTreats.Models;

namespace PierresTreats.Controllers
{ 
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Treats.ToList());
    }

        public async Task<ActionResult> MyTreat()
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      List<Treat> userItems = _db.Treats
                          .Where(entry => entry.User.Id == currentUser.Id)
                          .Include(item => item.TreatName)
                          .ToList();
      return View(userItems);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
  public ActionResult  Create(Treat treat)
      {
    
        _db.Treats.Add(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    

    public ActionResult Details(int id)
    {
      Treat thisTag = _db.Treats
          .Include(fish => fish.JoinEntities)
          .ThenInclude(fish => fish.Flavor)
          .FirstOrDefault(tag => tag.TreatId == id);
      return View(thisTag);
    }

    public ActionResult Edit(int id)
    {
      Treat thisTag = _db.Treats.FirstOrDefault(tag => tag.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTag);

    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Treats.Update(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Treat thisTag = _db.Treats.FirstOrDefault(tag => tag.TreatId == id);
      return View(thisTag);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTag = _db.Treats.FirstOrDefault(tag => tag.TreatId == id);
      _db.Treats.Remove(thisTag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      Treat thisTag = _db.Treats
                          .FirstOrDefault(tags => tags.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTag);
    }

    [HttpPost]
    public ActionResult AddTreat(Treat treat, int flavorId)
    {
      #nullable enable
      FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
      #nullable disable
      if (joinEntity == null && flavorId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


  }
}

PierreTreats/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Treat

<h4>Assign a Treat to Flavor: @Html.DisplayFor(model => model.TreatName)</h4>

<ul>
  @foreach (FlavorTreat join in Model.JoinEntities)
  {
      <li><strong>@join.Flavor.FlavorName</strong></li>
    @using (Html.BeginForm("DeleteJoin", "Treats"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatId)
      <input type="submit" value="Delete" />
    }
  }
</ul>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)
  @Html.Label("Select Flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="Save" />
}
<br>
<p>@Html.ActionLink("Back to All Treats", "Index")</p>

PierreTreats/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<p>@Html.ValidationMessageFor(model => model.TreatId, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
<p>@Html.ValidationMessageFor(model => model.TreatName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

<h1> Add a new Treat </h1>

@using(Html.BeginForm())
{
    @Html.LabelFor(model => model.TreatName)
    @Html.TextBoxFor(model => model.TreatName)
<br>
<input type="submit" value="Add new Category" class="button" />
}

PierreTreats/Views/Treats/Delete.cshtml
@{
    Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h4>Delete a Treat?</h4>

@Html.DisplayFor(model => model.TreatName)
@using (Html.BeginForm())
{
    <input type="submit" class="button" value="Delete"/>
}
<br>
@Html.ActionLink("Back to all Treats", "Index")

PierreTreats/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Treat

<h1>Treat Details</h1>
<hr />

<h3>@Html.DisplayFor(model => model.TreatName):</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This Treat does not belong to any Flavors!</p> 
}
else
{
  <h4>Flavors that include this Treat:</h4>
  <ul>
  @foreach(FlavorTreat join in Model.JoinEntities)
  {
    <li><strong>@Html.ActionLink($"{join.Flavor.FlavorName}", "Details", "Flavors", new { id = join.FlavorId})</strong></li>
  }

  </ul>
}


<a href='@Url.Action("Delete")'>
  <button type="button" class="button">Delete</button>
</a>

PierreTreats/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Edit</h2>

<h4>Edit this Treat: @Html.DisplayFor(model => model.TreatName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.LabelFor(model => model.TreatName)
    @Html.EditorFor(model => model.TreatName)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

PierreTreats/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models;

<h1>List of  Treats</h1>

@if (@Model.Count == 0)
{
    <h3> No Treats have been added</h3>
    
}

@foreach (Treat item in Model)
{
    <li>@Html.ActionLink($"{item.TreatName}", "Details", new {id = item.TreatId})</li>
}
<br>
<a href='@Url.Action("Create")'>
    <button type="button" class="button">New Treat</button>
</a>

PierreTreats/Views/Treats/MyTreat.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models;

<h1>@User.Identity.Name</h1>

@if (@Model.Count == 0)
{
  <h3>No Treats have been added yet!</h3>
} 
else
{
  <ul>
    @foreach (Treat item in Model)
    {
      <li>@Html.ActionLink($"{item.TreatName}", "Details", new { id = item.TreatId }) </li>
    }
  </ul>
}
<a href='@Url.Action("Create")'>
    <button type="button" class="button">New Treat</button>
</a>
<a href='@Url.Action("Index")'>
    <button type="button" class="button">Back</button>
</a>